//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTabaniIslemleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veri
    {
        public int KisiID { get; set; }
        public string Isim { get; set; }
        public string Soyisim { get; set; }
        public double Tel { get; set; }
        public string Cinsiyet { get; set; }
    }
}
